/* Automatically generated by po2tbl.sed from mydict.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"mydict", 2},
  {" Quit ", 3},
  {"Give me comments", 4},
  {"Popup Recite", 5},
  {"  MyDict , Powered by brains.  ", 6},
  {"Reference", 7},
  {" What is: ", 8},
  {"Click Right button to clear the entry", 9},
  {" Search ", 10},
  {"Look up ", 11},
  {"Add", 12},
  {"Need to remember", 13},
  {"Relative Words", 14},
  {"label9", 15},
  {"\
\n\
Welcome to gnuDict framework - mydict-client Gtk version\n\
\n\
\n\
\n\
\n\
\n\
Now check the plugins .......", 16},
  {"Welcome to mydict", 17},
  {"Preference", 18},
  {"MyDict", 19},
  {"\
GNU Dict - Dictionary Framework\n\
- mydict-client package\n\
MyDict\n\
Author : Larry Cai <caiyu@yahoo.com>", 20},
  {"Techonology", 21},
  {"\
Please visit\n\
http://sourceforge.net/projects/gnudict\n\
for the Dictionary Techonology\n\
\n\
Powered by Glade & Brains\n\
\n\
\n", 22},
  {"use locale for translation", 23},
  {"About", 24},
  {" Dict", 25},
  {"reload my plugins", 26},
  {"Recite", 27},
  {"Interval:", 28},
  {"Default", 29},
  {"Update", 30},
  {"seconds", 31},
  {"Recite Database", 32},
  {"Recite database list", 33},
  {"reload list", 34},
  {"Options", 35},
  {"Quit", 36},
  {"Thank you for using myDict", 37},
  {"Debug", 38},
  {"Remove", 39},
  {"Pause", 40},
  {"Display: ", 41},
  {"Word", 42},
  {"Phonetic", 43},
  {"Translation", 44},
  {"Back", 45},
  {"Next", 46},
  {"Couldn't find pixmap file: %s", 47},
  {"Error loading pixmap file: %s", 48},
};

int _msg_tbl_length = 48;
