gcc -o build/unix/Errors.o -c -std=c99 -Wa,-adhlns=build/unix/Errors.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL Errors.c
gcc -o build/unix/LoadBlock.o -c -std=c99 -Wa,-adhlns=build/unix/LoadBlock.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL LoadBlock.c
gcc -o build/unix/apps/Benchmarks.o -c -std=c99 -Wa,-adhlns=build/unix/apps/Benchmarks.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL apps/Benchmarks.c
gcc -o build/unix/ui/MorseBox.o -c -std=c99 -Wa,-adhlns=build/unix/ui/MorseBox.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL ui/MorseBox.c
gcc -o build/unix/ui/ListView.o -c -std=c99 -Wa,-adhlns=build/unix/ui/ListView.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL ui/ListView.c
gcc -o build/unix/ui/ListCmdr.o -c -std=c99 -Wa,-adhlns=build/unix/ui/ListCmdr.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL ui/ListCmdr.c
ar rc build/unix/ui/libUi.a build/unix/ui/MorseBox.o build/unix/ui/ListView.o build/unix/ui/ListCmdr.o
ranlib build/unix/ui/libUi.a
gcc -o build/unix/platform/PosixPlatform.o -c -std=c99 -Wa,-adhlns=build/unix/platform/PosixPlatform.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL platform/PosixPlatform.c
gcc -o build/unix/platform/Platform.o -c -std=c99 -Wa,-adhlns=build/unix/platform/Platform.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL platform/Platform.c
platform/Platform.c: In function 'InputUnescape':
platform/Platform.c:4: warning: comparison is always true due to limited range of data type
gcc -o build/unix/platform/vt52.o -c -std=c99 -Wa,-adhlns=build/unix/platform/vt52.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL platform/vt52.c
gcc -o build/unix/platform/FileStdio.o -c -std=c99 -Wa,-adhlns=build/unix/platform/FileStdio.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL platform/FileStdio.c
ar rc build/unix/platform/libPlatform.a build/unix/platform/PosixPlatform.o build/unix/platform/Platform.o build/unix/platform/vt52.o build/unix/platform/FileStdio.o
ranlib build/unix/platform/libPlatform.a
gcc -o build/unix/bgtree/bgCore.o -c -std=c99 -Wa,-adhlns=build/unix/bgtree/bgCore.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL bgtree/bgCore.c
gcc -o build/unix/bgtree/bgUtil.o -c -std=c99 -Wa,-adhlns=build/unix/bgtree/bgUtil.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL bgtree/bgUtil.c
gcc -o build/unix/bgtree/crc32.o -c -std=c99 -Wa,-adhlns=build/unix/bgtree/crc32.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL bgtree/crc32.c
gcc -o build/unix/bgtree/ar.o -c -std=c99 -Wa,-adhlns=build/unix/bgtree/ar.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL bgtree/ar.c
gcc -o build/unix/bgtree/bgApi.o -c -std=c99 -Wa,-adhlns=build/unix/bgtree/bgApi.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL bgtree/bgApi.c
gcc -o build/unix/bgtree/bgUtil2.o -c -std=c99 -Wa,-adhlns=build/unix/bgtree/bgUtil2.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL bgtree/bgUtil2.c
ar rc build/unix/bgtree/libbgTree.a build/unix/bgtree/bgCore.o build/unix/bgtree/bgUtil.o build/unix/bgtree/crc32.o build/unix/bgtree/ar.o build/unix/bgtree/bgApi.o build/unix/bgtree/bgUtil2.o
ranlib build/unix/bgtree/libbgTree.a
ar rc build/unix/libLoadBlock.a build/unix/LoadBlock.o
ranlib build/unix/libLoadBlock.a
ar rc build/unix/libErrors.a build/unix/Errors.o
ranlib build/unix/libErrors.a
gcc -o build/unix/uCmorse/uCmorse.o -c -std=c99 -Wa,-adhlns=build/unix/uCmorse/uCmorse.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL uCmorse/uCmorse.c
ar rc build/unix/uCmorse/libuCmorse.a build/unix/uCmorse/uCmorse.o
ranlib build/unix/uCmorse/libuCmorse.a
gcc -o build/unix/uCmorse/inmorse.o -c -std=c99 -Wa,-adhlns=build/unix/uCmorse/inmorse.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL uCmorse/inmorse.c
ar rc build/unix/uCmorse/libinmorse.a build/unix/uCmorse/inmorse.o
ranlib build/unix/uCmorse/libinmorse.a
gcc -o build/unix/apps/Benchmarks -Wl,-Map,build/unix/apps/Benchmarks.map -Wl,-gc-sections -Wl,--relax build/unix/apps/Benchmarks.o -Lbuild/unix -L. -Lbuild/unix/bgtree -Lbgtree -Lbuild/unix/uCmorse -LuCmorse -Lbuild/unix/platform -Lplatform -Lbuild/unix/ui -Lui -Lbuild/unix/apps -Lapps -Lbuild/unix/pfatfs-stdio -Lpfatfs-stdio -lUi -lPlatform -lbgTree -lLoadBlock -lErrors -luCmorse -linmorse
gcc -o build/unix/apps/ViewFile.o -c -std=c99 -Wa,-adhlns=build/unix/apps/ViewFile.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL apps/ViewFile.c
gcc -o build/unix/apps/ViewFile -Wl,-Map,build/unix/apps/ViewFile.map -Wl,-gc-sections -Wl,--relax build/unix/apps/ViewFile.o -Lbuild/unix -L. -Lbuild/unix/bgtree -Lbgtree -Lbuild/unix/uCmorse -LuCmorse -Lbuild/unix/platform -Lplatform -Lbuild/unix/ui -Lui -Lbuild/unix/apps -Lapps -Lbuild/unix/pfatfs-stdio -Lpfatfs-stdio -lUi -lPlatform -lbgTree -lLoadBlock -lErrors -luCmorse -linmorse
gcc -o build/unix/apps/WikiApp.o -c -std=c99 -Wa,-adhlns=build/unix/apps/WikiApp.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL apps/WikiApp.c
gcc -o build/unix/apps/WikiMain.o -c -std=c99 -Wa,-adhlns=build/unix/apps/WikiMain.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL apps/WikiMain.c
gcc -o build/unix/apps/WikiUtil.o -c -std=c99 -Wa,-adhlns=build/unix/apps/WikiUtil.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL apps/WikiUtil.c
ar rc build/unix/apps/libWikiApp.a build/unix/apps/WikiApp.o build/unix/apps/WikiUtil.o
ranlib build/unix/apps/libWikiApp.a
gcc -o build/unix/apps/WikiMain -Wl,-Map,build/unix/apps/WikiMain.map -Wl,-gc-sections -Wl,--relax build/unix/apps/WikiMain.o -Lbuild/unix -L. -Lbuild/unix/bgtree -Lbgtree -Lbuild/unix/uCmorse -LuCmorse -Lbuild/unix/platform -Lplatform -Lbuild/unix/ui -Lui -Lbuild/unix/apps -Lapps -Lbuild/unix/pfatfs-stdio -Lpfatfs-stdio -lWikiApp -lUi -lPlatform -lbgTree -lLoadBlock -lErrors -luCmorse -linmorse
gcc -o build/unix/bgtree/artest.o -c -std=c99 -Wa,-adhlns=build/unix/bgtree/artest.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL bgtree/artest.c
gcc -o build/unix/bgtree/artest -Wl,-Map,build/unix/bgtree/artest.map -Wl,-gc-sections -Wl,--relax build/unix/bgtree/artest.o build/unix/bgtree/ar.o -Lbuild/unix -L. -Lbuild/unix/bgtree -Lbgtree -Lbuild/unix/uCmorse -LuCmorse -Lbuild/unix/platform -Lplatform -Lbuild/unix/ui -Lui -Lbuild/unix/apps -Lapps -Lbuild/unix/pfatfs-stdio -Lpfatfs-stdio -lSDL
gcc -o build/unix/bgtree/bgTest.o -c -std=c99 -Wa,-adhlns=build/unix/bgtree/bgTest.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL bgtree/bgTest.c
gcc -o build/unix/bgtree/bgTest -Wl,-Map,build/unix/bgtree/bgTest.map -Wl,-gc-sections -Wl,--relax build/unix/bgtree/bgTest.o -Lbuild/unix/bgtree -Lbgtree -Lbuild/unix -L. -lbgTree -lErrors
gcc -o build/unix/bgtree/bgTree.o -c -std=c99 -Wa,-adhlns=build/unix/bgtree/bgTree.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL bgtree/bgTree.c
gcc -o build/unix/bgtree/bgTreeCmd -Wl,-Map,build/unix/bgtree/bgTreeCmd.map -Wl,-gc-sections -Wl,--relax build/unix/bgtree/bgTree.o -Lbuild/unix/bgtree -Lbgtree -Lbuild/unix -L. -lbgTree -lErrors
g++ -o build/unix/tests/FsTest.o -c -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL tests/FsTest.cpp
g++ -o build/unix/tests/FsTest -Wl,-Map,build/unix/tests/FsTest.map -Wl,-gc-sections -Wl,--relax build/unix/tests/FsTest.o -Lbuild/unix -L. -Lbuild/unix/bgtree -Lbgtree -Lbuild/unix/uCmorse -LuCmorse -Lbuild/unix/platform -Lplatform -Lbuild/unix/ui -Lui -Lbuild/unix/apps -Lapps -Lbuild/unix/pfatfs-stdio -Lpfatfs-stdio -lUi -lPlatform -lbgTree -lLoadBlock -lErrors -luCmorse -linmorse
gcc -o build/unix/tests/test_Input.o -c -std=c99 -Wa,-adhlns=build/unix/tests/test_Input.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL tests/test_Input.c
gcc -o build/unix/tests/test_Input -Wl,-Map,build/unix/tests/test_Input.map -Wl,-gc-sections -Wl,--relax build/unix/tests/test_Input.o -Lbuild/unix -L. -Lbuild/unix/bgtree -Lbgtree -Lbuild/unix/uCmorse -LuCmorse -Lbuild/unix/platform -Lplatform -Lbuild/unix/ui -Lui -Lbuild/unix/apps -Lapps -Lbuild/unix/pfatfs-stdio -Lpfatfs-stdio -lUi -lPlatform -lbgTree -lLoadBlock -lErrors -luCmorse -linmorse
gcc -o build/unix/tests/test_ListCmdr.o -c -std=c99 -Wa,-adhlns=build/unix/tests/test_ListCmdr.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL tests/test_ListCmdr.c
gcc -o build/unix/tests/test_ListCmdr -Wl,-Map,build/unix/tests/test_ListCmdr.map -Wl,-gc-sections -Wl,--relax build/unix/tests/test_ListCmdr.o -Lbuild/unix -L. -Lbuild/unix/bgtree -Lbgtree -Lbuild/unix/uCmorse -LuCmorse -Lbuild/unix/platform -Lplatform -Lbuild/unix/ui -Lui -Lbuild/unix/apps -Lapps -Lbuild/unix/pfatfs-stdio -Lpfatfs-stdio -lUi -lPlatform -lbgTree -lLoadBlock -lErrors -luCmorse -linmorse
gcc -o build/unix/tests/test_MorseBox.o -c -std=c99 -Wa,-adhlns=build/unix/tests/test_MorseBox.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL tests/test_MorseBox.c
gcc -o build/unix/tests/test_MorseBox -Wl,-Map,build/unix/tests/test_MorseBox.map -Wl,-gc-sections -Wl,--relax build/unix/tests/test_MorseBox.o -Lbuild/unix -L. -Lbuild/unix/bgtree -Lbgtree -Lbuild/unix/uCmorse -LuCmorse -Lbuild/unix/platform -Lplatform -Lbuild/unix/ui -Lui -Lbuild/unix/apps -Lapps -Lbuild/unix/pfatfs-stdio -Lpfatfs-stdio -lUi -lPlatform -lbgTree -lLoadBlock -lErrors -luCmorse -linmorse
gcc -o build/unix/tests/test_WikiApp.o -c -std=c99 -Wa,-adhlns=build/unix/tests/test_WikiApp.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL tests/test_WikiApp.c
gcc -o build/unix/tests/test_WikiApp -Wl,-Map,build/unix/tests/test_WikiApp.map -Wl,-gc-sections -Wl,--relax build/unix/tests/test_WikiApp.o -Lbuild/unix -L. -Lbuild/unix/bgtree -Lbgtree -Lbuild/unix/uCmorse -LuCmorse -Lbuild/unix/platform -Lplatform -Lbuild/unix/ui -Lui -Lbuild/unix/apps -Lapps -Lbuild/unix/pfatfs-stdio -Lpfatfs-stdio -lWikiApp -lUi -lPlatform -lbgTree -lLoadBlock -lErrors -luCmorse -linmorse
gcc -o build/unix/tests/test_vt52.o -c -std=c99 -Wa,-adhlns=build/unix/tests/test_vt52.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL tests/test_vt52.c
gcc -o build/unix/tests/test_vt52 -Wl,-Map,build/unix/tests/test_vt52.map -Wl,-gc-sections -Wl,--relax build/unix/tests/test_vt52.o -Lbuild/unix -L. -Lbuild/unix/bgtree -Lbgtree -Lbuild/unix/uCmorse -LuCmorse -Lbuild/unix/platform -Lplatform -Lbuild/unix/ui -Lui -Lbuild/unix/apps -Lapps -Lbuild/unix/pfatfs-stdio -Lpfatfs-stdio -lUi -lPlatform -lbgTree -lLoadBlock -lErrors -luCmorse -linmorse
gcc -o build/unix/uCmorse/test_inmorse.o -c -std=c99 -Wa,-adhlns=build/unix/uCmorse/test_inmorse.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL uCmorse/test_inmorse.c
gcc -o build/unix/uCmorse/test_inmorse -Wl,-Map,build/unix/uCmorse/test_inmorse.map -Wl,-gc-sections -Wl,--relax build/unix/uCmorse/test_inmorse.o -Lbuild/unix/uCmorse -LuCmorse -linmorse
gcc -o build/unix/uCmorse/test_morse.o -c -std=c99 -Wa,-adhlns=build/unix/uCmorse/test_morse.o.lst -Winvalid-pch -Wall -Wno-long-long -pedantic -O0 -ggdb -D_USE_LSEEK -D_WRITE_FUNC -D_GNU_SOURCE=1 -D_REENTRANT -Ibuild/unix -I. -I. -Ibgtree -IuCmorse -Iplatform -Iui -Iapps -Ipfatfs-stdio -I/usr/local/jlime/mipsel-toolchain/usr/include/SDL uCmorse/test_morse.c
gcc -o build/unix/uCmorse/test_morse -Wl,-Map,build/unix/uCmorse/test_morse.map -Wl,-gc-sections -Wl,--relax build/unix/uCmorse/test_morse.o -Lbuild/unix/uCmorse -LuCmorse -luCmorse
