/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>
#include <locale.h>

#include "interface.h"
#include "support.h"
#include "mydict.h"

// #define PACKAGE_LOCALE_DIR "/usr/share/locale"

int
main (int argc, char *argv[])
{
  GtkWidget *window1;
  
#ifdef ENABLE_NLS
//	g_print("%s %s\n",PACKAGE,PACKAGE_LOCALE_DIR);
  bindtextdomain (PACKAGE, PACKAGE_LOCALE_DIR);
  textdomain (PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  char *para=(char *)NULL;
  if(argc>1)
  	para=argv[1];
	
  add_pixmap_directory (PACKAGE_DATA_DIR "../pixmaps");
  add_pixmap_directory (PACKAGE_SOURCE_DIR "../pixmaps");
  add_pixmap_directory("./pixmaps");
  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window1 = create_window1 ();
  
  gtk_widget_show (window1);

  init_gdict(window1,para); 
 
  gtk_main ();
  return 0;
}

