#!/bin/sh

#This creates a binary tarball for the GP2X.
#NOTE: This is run when executing 'make -f Makefile.gp2x'. It also
#expects PACKAGE_DATA_DIR to have been exported.

if test -a VERSION ; then
	VERSION="$(cat VERSION)"
	if test -a TARGET ; then
		TARGET="$(cat TARGET)"
		if [ -n "$PACKAGE_DATA_DIR" ] ; then
#-------------------------------------------------------------
			echo "Building GP2X binary tarball..."
			
			mkdir -p ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/levels
			mkdir -p ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/sounds/default
			mkdir -p ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/sounds/oily
			mkdir -p ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/sounds/skins
			mkdir -p ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/rob
			mkdir -p ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/skins/original
			mkdir -p ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/skins/tronic
			mkdir -p ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/skins/oily
			mkdir -p ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/locales/en_GB
			mkdir -p ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/locales/pl_PL
			mkdir -p ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/locales/de_DE
			mkdir -p ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/locales/sk_SK
			mkdir -p ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/locales/sv_SE
			mkdir -p ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/locales/ru_RU
			mkdir -p ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/locales/id_ID
			
			cp data/levels/* ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/levels/
			cp data/sounds/default/* ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/sounds/default/
			cp data/sounds/oily/* ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/sounds/oily/
			cp data/sounds/skins/* ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/sounds/skins/
			cp data/rob/*.bmp ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/rob/
			cp data/skins/original/*16.bmp data/skins/original/*16.png data/skins/original/skinrc ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/skins/original/
			cp data/skins/tronic/*16.bmp data/skins/tronic/*16.png data/skins/tronic/skinrc ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/skins/tronic/
			cp data/skins/oily/*16.bmp data/skins/oily/*16.png data/skins/oily/skinrc ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/skins/oily/
			if [ -n "$FONT_USE_SDL_TTF" ] ; then
				cp data/skins/original/robbo.ttf ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/skins/original/
				cp data/skins/tronic/robbo.ttf ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/skins/tronic/
				cp data/skins/oily/robbo.ttf ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/skins/oily/
			fi
			cp data/locales/en_GB/* ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/locales/en_GB/
			cp data/locales/pl_PL/* ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/locales/pl_PL/
			cp data/locales/de_DE/* ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/locales/de_DE/
			cp data/locales/sk_SK/* ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/locales/sk_SK/
			cp data/locales/sv_SE/* ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/locales/sv_SE/
			cp data/locales/ru_RU/* ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/locales/ru_RU/
			cp data/locales/id_ID/* ${TARGET}_${VERSION}_gp2x/${PACKAGE_DATA_DIR}/locales/id_ID/

			cp icon32.png ${TARGET}_${VERSION}_gp2x/${TARGET}.png
			cp ${TARGET} gp2x/${TARGET}.gpe ${TARGET}_${VERSION}_gp2x/
			cat README.gp2x README > ${TARGET}_${VERSION}_gp2x/readme.txt
			cp ChangeLog NEWS COPYING LICENSE-sound ${TARGET}_${VERSION}_gp2x/
			if [ -n "$FONT_USE_SDL_TTF" ] ; then
				cp LICENSE-ttf ${TARGET}_${VERSION}_gp2x/
			fi
			
			tar czvf ${TARGET}_${VERSION}_gp2x.tar.gz ${TARGET}_${VERSION}_gp2x
			
			rm -rf ${TARGET}_${VERSION}_gp2x
			
			echo "All done."
#-------------------------------------------------------------
		else
			echo "ERROR: Variable \"PACKAGE_DATA_DIR\" has not been set/exported."
		fi
	else
		echo "ERROR: File \"TARGET\" not found. This is a text file with the project name inside it."
	fi
else
	echo "ERROR: File \"VERSION\" not found. This is a text file with the version number inside it."
fi
